name: rastreador_app_flutter
description: Um novo projeto Flutter para rastreamento e agendamento.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # DEPENDÊNCIAS DE TERCEIROS
  google_fonts: ^6.2.1
  http: ^1.2.1 # Versão atualizada para a mais estável
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.12
  cupertino_icons: ^1.0.8 # Versão atualizada
  lucide_icons_flutter: ^1.0.0 # Mantido para corresponder à sua lista original
  go_router: ^14.2.0
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  jwt_decoder: ^2.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/background.png
